### ISSUE TITLE
FNP header

### ISSUE THREAD

**Issue by michalkouril** [mwrnd/innova2_flex_xcku15p_notes#10]
I didn't see this in your outstanding write up -- next to the JTAG connector there is an unpopulated FNP header -- I believe it stands for Firmware Not Present. Shorting it boots the card into the firmware recovery. It seems more convenient than shorting the FLASH IC pins (and you can leave the short in place while reprogramming the firmware).

**Comment by mwrnd** [comment]
Thanks [michalkouril](https://github.com/michalkouril)! I first tried shorting the header with a 1k resistor and then a proper short and both caused the board to boot into Firmware Recovery Mode. Thanks for the tip! I was unaware this is what FNP stood for. I have [updated my notes](https://github.com/mwrnd/innova2_flex_xcku15p_notes?tab=readme-ov-file#programming-the-connectx5-flash-by-forcing-recovery-mode-using-fnp-header).

![FNP_Header_Shorted_with_1k_Resistor](https://github.com/user-attachments/assets/58894c08-ab81-4684-845c-ce7b917fbe86)
