### ISSUE TITLE
FPGA Not Appearing after Rescan

### ISSUE THREAD

**Issue by doihead** [mwrnd/innova2_flex_xcku15p_notes#6]
I've been able to follow your tutorial and build a bitstream with and have it show up when I do lspci and now I'm trying to remove and reenumerate the FPGA so I can flash a new bitstream without having to restart my computer. When I remove the FPGA by running `echo 1 > /sys/bus/pci/devices/0000\:03\:00.0/remove`, everything works as I'd expect it to, with the Xilinx RAM device disappearing, but when I try and rescan the bus without doing anything in between using `echo 1 > /sys/bus/pci/rescan`, it doesn't show up in lspci. I have to reboot the computer before the FPGA shows up again. This procedure works when I attempt to remove and reenumerate other parts of the card like the Ethernet controllers or the PCIe switches, just not for the FPGA.
So far I have tried removing all PCIe devices associated with the Innova-2 Flex NIC before rescanning and the steps you listed for disabling and reenabling the PCIe switch with no luck. Do you have any suggestions for what's going on and is there any information I can provide?
Thanks!

**Comment by mwrnd** [comment]
This has been answered in the [Innova 2 FPGA PCIE Rescan Not Showing Up](https://forums.developer.nvidia.com/t/innova-2-fpga-pcie-rescan-not-showing-up/270760) thread on the [Nvidia Developer Forums](https://forums.developer.nvidia.com).

I have added the [innova2_xdma_demo](https://github.com/mwrnd/innova2_xdma_demo) project which includes detailed instructions and demonstration files for [Loading Updated Designs Using JTAG](https://github.com/mwrnd/innova2_xdma_demo/tree/ae290acc56fcc7935e1a39c12e00df31371da965#loading-updated-designs-using-jtag). It works on my [Intel B360](https://www.intel.com/content/www/us/en/products/sku/133332/intel-b360-chipset/specifications.html) system running Ubuntu 20.04 and Linux Kernel `5.8.0-43-generic`.
